### ISSUE TITLE
Ppx version constraint missing on NixOS unstable/22.11

### ISSUE THREAD

**Issue by cmovcc** [hacl-star/hacl-nix#1]
Hello!

Using this derivation using NixOS unstable (and the soon-to-be-released 22.11 channel) fails, as there is not yet a ppx version constraint.
I submit a rough PR as a fix, more as a PoC than as a production-ready clean fix, reusing this fix: https://github.com/NixOS/nixpkgs/pull/195515 .

By the way, would it make sense to enable strictDeps, that is iirc to distinguish better what is a build dependency and what is a runtime dependency? It seems to be that many packages seem to be required for the build (I checked this using `nix build --dry-run`), I have very possibly missed something.

Thank you very much for your work!

**Comment by pnmadelaine** [comment]
Thanks for your interest and for your work.
These expressions were really intended to be built with the locked version of nixpkgs, we didn't take any care to make them portable. The goal had always been to move them to their respective repositories anyway, which is now done.
In the meantime the build process for F* was heavily modified. Please check out the F* repository!
I'm closing this, together with #2, since it is no longer relevant to this repository.
